import { Question } from '../types';

export const CURATED_QUESTION_BANK: Question[] = [
  // ==================== IMO (MATHEMATICS) ====================
  // Grade 4 - Fractions
  {
    id: 'imo_g4_frac_1',
    question: 'What is 3/4 of 24?',
    options: ['12', '16', '18', '20'],
    correctAnswer: '18',
    correctOptionIndex: 2,
    explanation: 'To find 3/4 of 24, first divide 24 by 4 to get one part: 24 ÷ 4 = 6. Then multiply by 3: 6 × 3 = 18.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Fractions',
    difficulty: 'Medium',
    sourceType: 'generated',
    hints: ['Divide 24 by 4 first, then multiply the result by 3.'],
  },
  {
    id: 'imo_g4_frac_2',
    question: 'A pizza is cut into 8 equal slices. Leo ate 3 slices and Maya ate 2 slices. What fraction of the pizza is left?',
    options: ['3/8', '5/8', '2/8', '4/8'],
    correctAnswer: '3/8',
    correctOptionIndex: 0,
    explanation: 'Total slices = 8. Leo and Maya ate 3 + 2 = 5 slices. The remaining slices are 8 - 5 = 3 slices. So the fraction left is 3/8.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Fractions',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_num_1',
    question: 'Which of the following numbers has the digit 7 in the thousands place and 4 in the tens place?',
    options: ['47,340', '74,520', '37,249', '71,400'],
    correctAnswer: '37,249',
    correctOptionIndex: 2,
    explanation: 'In 37,249: 9 is in ones, 4 is in tens, 2 is in hundreds, and 7 is in thousands place. Thus, 7 is in the thousands place and 4 is in the tens place.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Numbers',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_geom_1',
    question: 'A rectangular garden has a length of 12 meters and a width of 7 meters. What is the perimeter of the garden?',
    options: ['19 meters', '38 meters', '84 meters', '42 meters'],
    correctAnswer: '38 meters',
    correctOptionIndex: 1,
    explanation: 'Perimeter of a rectangle = 2 × (Length + Width). Here, 2 × (12 + 7) = 2 × 19 = 38 meters.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Geometry',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_patt_1',
    question: 'Look at the pattern: 4, 9, 16, 25, 36, ___ . What is the next number?',
    options: ['42', '45', '49', '50'],
    correctAnswer: '49',
    correctOptionIndex: 2,
    explanation: 'These are square numbers: 2×2=4, 3×3=9, 4×4=16, 5×5=25, 6×6=36. The next is 7×7 = 49 (or difference adds +5, +7, +9, +11, so +13: 36+13=49).',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Patterns',
    difficulty: 'Hard',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_logic_1',
    question: 'Rohan is 4th from the front in a queue and 9th from the back. How many children are in the queue altogether?',
    options: ['11', '12', '13', '14'],
    correctAnswer: '12',
    correctOptionIndex: 1,
    explanation: 'Add both positions and subtract 1 (because Rohan was counted twice): 4 + 9 - 1 = 12 children in total.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Logical Reasoning',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },
  {
    id: 'imo_g4_time_1',
    question: 'A cartoon show starts at 4:45 PM and lasts for 1 hour and 35 minutes. At what time does it finish?',
    options: ['6:15 PM', '6:20 PM', '6:10 PM', '6:25 PM'],
    correctAnswer: '6:20 PM',
    correctOptionIndex: 1,
    explanation: '4:45 PM + 1 hour = 5:45 PM. Then add 15 minutes to reach 6:00 PM. The remaining 20 minutes (35 - 15) brings us to 6:20 PM.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Time',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_money_1',
    question: 'A notebook costs $4 and a pen costs $1.50. Priya buys 3 notebooks and 2 pens. She pays with a $20 note. How much change will she receive?',
    options: ['$5.00', '$4.50', '$6.00', '$3.50'],
    correctAnswer: '$5.00',
    correctOptionIndex: 0,
    explanation: '3 notebooks = 3 × $4 = $12. 2 pens = 2 × $1.50 = $3. Total spent = $12 + $3 = $15. Change = $20 - $15 = $5.00.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Money',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_word_1',
    question: 'There are 5 birds on each branch of a tree. If there are 8 branches, and 6 birds fly away, how many birds remain?',
    options: ['40', '36', '34', '32'],
    correctAnswer: '34',
    correctOptionIndex: 2,
    explanation: 'Total initial birds = 5 × 8 = 40. When 6 birds fly away: 40 - 6 = 34 birds remain.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Word Problems',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 3 - IMO
  {
    id: 'imo_g3_num_1',
    question: 'What is the sum of the place values of 5 in the number 5,352?',
    options: ['500', '5,050', '5,500', '5,005'],
    correctAnswer: '5,050',
    correctOptionIndex: 1,
    explanation: 'In 5,352, the first 5 is in the thousands place (5,000) and the second 5 is in the tens place (50). The sum is 5,000 + 50 = 5,050.',
    subject: 'IMO',
    grade: 'Grade 3',
    topic: 'Numbers',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g3_mult_1',
    question: 'If 7 boxes each contain 6 crayons, how many crayons are there altogether?',
    options: ['36', '40', '42', '48'],
    correctAnswer: '42',
    correctOptionIndex: 2,
    explanation: 'Multiply the number of boxes by crayons per box: 7 × 6 = 42 crayons.',
    subject: 'IMO',
    grade: 'Grade 3',
    topic: 'Multiplication & Division',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - IMO
  {
    id: 'imo_g5_dec_1',
    question: 'Calculate: 3.45 + 0.8 - 1.25',
    options: ['2.90', '3.00', '3.10', '3.20'],
    correctAnswer: '3.00',
    correctOptionIndex: 1,
    explanation: '3.45 + 0.8 = 4.25. Then 4.25 - 1.25 = 3.00.',
    subject: 'IMO',
    grade: 'Grade 5',
    topic: 'Decimals',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g5_chall_1',
    question: 'In a farm, there are cows and ducks. Together they have 20 heads and 56 legs. How many cows are there?',
    options: ['6', '8', '10', '12'],
    correctAnswer: '8',
    correctOptionIndex: 1,
    explanation: 'Let cows be C and ducks be D. C + D = 20. Cows have 4 legs and ducks have 2 legs: 4C + 2D = 56. If all 20 were ducks: 20 × 2 = 40 legs. Extra legs = 56 - 40 = 16. Each cow gives 2 extra legs (4 - 2 = 2). Number of cows = 16 ÷ 2 = 8 cows!',
    subject: 'IMO',
    grade: 'Grade 5',
    topic: 'Logical Reasoning',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },

  // ==================== ISO (SCIENCE) ====================
  // Grade 4 - Plants
  {
    id: 'iso_g4_plant_1',
    question: 'Which green pigment in leaves captures sunlight to help plants prepare their own food?',
    options: ['Stomata', 'Chlorophyll', 'Glucose', 'Xylem'],
    correctAnswer: 'Chlorophyll',
    correctOptionIndex: 1,
    explanation: 'Chlorophyll is the green pigment inside plant chloroplasts that traps solar energy from sunlight during photosynthesis.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Plants',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_plant_2',
    question: 'Desert plants like cactus have spines instead of wide green leaves. What is the main reason for this adaptation?',
    options: ['To absorb more sunlight', 'To reduce water loss through transpiration', 'To attract insects for pollination', 'To store extra soil minerals'],
    correctAnswer: 'To reduce water loss through transpiration',
    correctOptionIndex: 1,
    explanation: 'Spines have very little surface area compared to broad leaves. This minimizes evaporation and water loss in dry, hot desert environments.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Plants',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  // Grade 4 - Animals
  {
    id: 'iso_g4_anim_1',
    question: 'Which of the following animals breathes through both its moist skin in water and lungs on land?',
    options: ['Crocodile', 'Frog', 'Dolphin', 'Earthworm'],
    correctAnswer: 'Frog',
    correctOptionIndex: 1,
    explanation: 'Frogs are amphibians. On land they breathe using their lungs, while in water they absorb oxygen directly through their moist skin.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Animals',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  // Grade 4 - Human Body
  {
    id: 'iso_g4_body_1',
    question: 'Which organ pumps oxygen-rich blood to all parts of the human body?',
    options: ['Lungs', 'Heart', 'Stomach', 'Kidneys'],
    correctAnswer: 'Heart',
    correctOptionIndex: 1,
    explanation: 'The heart acts as a muscular pump that continuously beats to circulate blood through blood vessels to every cell in the body.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Body',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Force & Motion
  {
    id: 'iso_g4_force_1',
    question: 'Why do bicycle brakes make a rolling bike slow down and stop when pressed against the wheel rim?',
    options: ['Gravitational pull increases', 'Friction opposes the motion', 'Magnetic repulsion acts on tires', 'Air pressure drops instantly'],
    correctAnswer: 'Friction opposes the motion',
    correctOptionIndex: 1,
    explanation: 'When brake pads press against the rim, friction is created between the two surfaces. Friction always opposes motion, causing the bicycle to slow down.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Force & Motion',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  // Grade 4 - Space
  {
    id: 'iso_g4_space_1',
    question: 'Earth experiences day and night primarily because of which movement?',
    options: ['Revolution around the Sun', 'Rotation on its own tilted axis', 'Gravitational pull of the Moon', 'Shifting of the Earth’s tectonic plates'],
    correctAnswer: 'Rotation on its own tilted axis',
    correctOptionIndex: 1,
    explanation: 'Earth spins (rotates) on its own axis once every 24 hours. The side facing the Sun has daylight, while the side turned away has night.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Space',
    difficulty: 'Medium',
    sourceType: 'previousYear',
  },
  // Grade 4 - Matter
  {
    id: 'iso_g4_matt_1',
    question: 'When water vapour cools down and turns back into tiny liquid droplets in the air, the process is called:',
    options: ['Evaporation', 'Precipitation', 'Condensation', 'Freezing'],
    correctAnswer: 'Condensation',
    correctOptionIndex: 2,
    explanation: 'Condensation occurs when a gas loses heat energy and transforms back into a liquid state, forming clouds or dew drops.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Matter',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Food & Nutrition
  {
    id: 'iso_g4_nutr_1',
    question: 'Which vitamin is synthesized by our skin when exposed to gentle morning sunlight and helps keep bones strong?',
    options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
    correctAnswer: 'Vitamin D',
    correctOptionIndex: 3,
    explanation: 'Our skin cells produce Vitamin D when exposed to sunlight. Vitamin D is essential for our body to absorb calcium and maintain strong bones and teeth.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Food & Nutrition',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 3 - ISO
  {
    id: 'iso_g3_anim_1',
    question: 'Which of these animals is an herbivore (eats only plants)?',
    options: ['Lion', 'Cow', 'Eagle', 'Shark'],
    correctAnswer: 'Cow',
    correctOptionIndex: 1,
    explanation: 'Herbivores are animals that eat only grass, leaves, and plant materials. Cows eat grass, making them herbivores.',
    subject: 'ISO',
    grade: 'Grade 3',
    topic: 'Animals',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - ISO
  {
    id: 'iso_g5_env_1',
    question: 'What is the greenhouse effect, and how does it impact planet Earth?',
    options: ['It cools the polar ice caps', 'Gases trap heat in the atmosphere, keeping Earth warm', 'It blocks all solar radiation from entering', 'It makes plants grow without sunlight'],
    correctAnswer: 'Gases trap heat in the atmosphere, keeping Earth warm',
    correctOptionIndex: 1,
    explanation: 'Greenhouse gases like carbon dioxide and water vapor absorb infrared heat radiated from Earth’s surface, trapping warmth in the lower atmosphere.',
    subject: 'ISO',
    grade: 'Grade 5',
    topic: 'Environment',
    difficulty: 'Hard',
    sourceType: 'generated',
  },

  // ==================== ICSO (COMPUTER SCIENCE) ====================
  // Grade 4 - Hardware
  {
    id: 'icso_g4_hard_1',
    question: 'Which component is commonly known as the "Brain" of the computer that performs calculations and carries out instructions?',
    options: ['RAM', 'Hard Drive', 'CPU (Central Processing Unit)', 'Motherboard'],
    correctAnswer: 'CPU (Central Processing Unit)',
    correctOptionIndex: 2,
    explanation: 'The CPU processes commands, calculates arithmetic equations, and manages operations, just like a brain coordinates the human body.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Hardware',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Input & Output Devices
  {
    id: 'icso_g4_io_1',
    question: 'Which of the following devices is solely an OUTPUT device?',
    options: ['Keyboard', 'Microphone', 'Monitor', 'Webcam'],
    correctAnswer: 'Monitor',
    correctOptionIndex: 2,
    explanation: 'A monitor displays visual output to the user. Keyboards, microphones, and webcams are input devices used to feed data into the computer.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Input & Output Devices',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Cyber Safety
  {
    id: 'icso_g4_cyber_1',
    question: 'Which of the following is the SAFEST password to use for an online learning account?',
    options: ['123456', 'myname123', 'B!ueSky#94', 'password'],
    correctAnswer: 'B!ueSky#94',
    correctOptionIndex: 2,
    explanation: 'A strong password combines uppercase letters, lowercase letters, numbers, and special symbols (! or #), making it very hard for unauthorized persons to guess.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Cyber Safety',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'icso_g4_cyber_2',
    question: 'If a stranger in an online multiplayer game asks you for your home address or phone number, what should you do?',
    options: [
      'Share it only if they seem friendly',
      'Never share personal info and tell a parent or teacher immediately',
      'Give them a friend’s address instead',
      'Ask them for their phone number first'
    ],
    correctAnswer: 'Never share personal info and tell a parent or teacher immediately',
    correctOptionIndex: 1,
    explanation: 'Never share your real name, address, school, or phone number online. Always inform a trusted adult if an unknown person asks for private information.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Cyber Safety',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Algorithms & Logic
  {
    id: 'icso_g4_algo_1',
    question: 'In computer science, what is an "Algorithm"?',
    options: [
      'A special computer monitor screen',
      'A step-by-step set of instructions to solve a problem',
      'A virus that erases all files',
      'A computer power cable'
    ],
    correctAnswer: 'A step-by-step set of instructions to solve a problem',
    correctOptionIndex: 1,
    explanation: 'An algorithm is an ordered sequence of clear instructions or steps designed to accomplish a specific task, such as a recipe or coding instructions.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Algorithms',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'icso_g4_code_1',
    question: 'A robot is programmed with this loop: REPEAT 4 TIMES [Move forward 1 step, Turn right 90 degrees]. What geometric shape will the robot trace on the floor?',
    options: ['Triangle', 'Square', 'Circle', 'Hexagon'],
    correctAnswer: 'Square',
    correctOptionIndex: 1,
    explanation: 'A square has 4 equal sides and four 90-degree right angle corners. Moving forward and turning 90 degrees 4 times returns the robot to the start in a square shape.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Coding Basics',
    difficulty: 'Hard',
    sourceType: 'previousYear',
  },
  {
    id: 'icso_g4_comp_1',
    question: 'Look at the sequence: 1010, 1020, 1040, 1070, ____. What is the next number in this sequence?',
    options: ['1090', '1100', '1110', '1120'],
    correctAnswer: '1110',
    correctOptionIndex: 2,
    explanation: 'Examine the differences between consecutive terms: 1020 - 1010 = +10, 1040 - 1020 = +20, 1070 - 1040 = +30. The next jump should be +40! So 1070 + 40 = 1110.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Computational Thinking',
    difficulty: 'Olympiad Challenge',
    sourceType: 'generated',
  },

  // Grade 3 - ICSO
  {
    id: 'icso_g3_basic_1',
    question: 'Which key on the keyboard is used to create a blank space between two words?',
    options: ['Enter Key', 'Spacebar', 'Shift Key', 'Backspace'],
    correctAnswer: 'Spacebar',
    correctOptionIndex: 1,
    explanation: 'The spacebar is the longest key on the keyboard, located at the bottom center. Pressing it inserts a single space between words.',
    subject: 'ICSO',
    grade: 'Grade 3',
    topic: 'Computer Basics',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - ICSO
  {
    id: 'icso_g5_net_1',
    question: 'What is the primary function of a Web Browser like Chrome or Firefox?',
    options: [
      'To build physical computer chips',
      'To retrieve, format, and display webpages from the internet',
      'To clean viruses from the hard drive',
      'To create PowerPoint presentations automatically'
    ],
    correctAnswer: 'To retrieve, format, and display webpages from the internet',
    correctOptionIndex: 1,
    explanation: 'A web browser is an application software used to navigate the World Wide Web, interpret HTML/CSS code, and render interactive webpages on your screen.',
    subject: 'ICSO',
    grade: 'Grade 5',
    topic: 'Internet',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
];
