import { Question } from '../types';

export const CURATED_QUESTION_BANK: Question[] = [
  // ==================== IMO (MATHEMATICS) ====================
  // Grade 4 - Fractions
  {
    id: 'imo_g4_frac_1',
    question: 'What is 3/4 of 24?',
    options: ['12', '16', '18', '20'],
    correctAnswer: '18',
    correctOptionIndex: 2,
    explanation: 'To find 3/4 of 24, first divide 24 by 4 to get one part: 24 ÷ 4 = 6. Then multiply by 3: 6 × 3 = 18.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Fractions',
    difficulty: 'Medium',
    sourceType: 'generated',
    hints: ['Divide 24 by 4 first, then multiply the result by 3.'],
  },
  {
    id: 'imo_g4_frac_2',
    question: 'A pizza is cut into 8 equal slices. Leo ate 3 slices and Maya ate 2 slices. What fraction of the pizza is left?',
    options: ['3/8', '5/8', '2/8', '4/8'],
    correctAnswer: '3/8',
    correctOptionIndex: 0,
    explanation: 'Total slices = 8. Leo and Maya ate 3 + 2 = 5 slices. The remaining slices are 8 - 5 = 3 slices. So the fraction left is 3/8.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Fractions',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_num_1',
    question: 'Which of the following numbers has the digit 7 in the thousands place and 4 in the tens place?',
    options: ['47,340', '74,520', '37,249', '71,400'],
    correctAnswer: '37,249',
    correctOptionIndex: 2,
    explanation: 'In 37,249: 9 is in ones, 4 is in tens, 2 is in hundreds, and 7 is in thousands place. Thus, 7 is in the thousands place and 4 is in the tens place.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Numbers',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_geom_1',
    question: 'A rectangular garden has a length of 12 meters and a width of 7 meters. What is the perimeter of the garden?',
    options: ['19 meters', '38 meters', '84 meters', '42 meters'],
    correctAnswer: '38 meters',
    correctOptionIndex: 1,
    explanation: 'Perimeter of a rectangle = 2 × (Length + Width). Here, 2 × (12 + 7) = 2 × 19 = 38 meters.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Geometry',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_patt_1',
    question: 'Look at the pattern: 4, 9, 16, 25, 36, ___ . What is the next number?',
    options: ['42', '45', '49', '50'],
    correctAnswer: '49',
    correctOptionIndex: 2,
    explanation: 'These are square numbers: 2×2=4, 3×3=9, 4×4=16, 5×5=25, 6×6=36. The next is 7×7 = 49 (or difference adds +5, +7, +9, +11, so +13: 36+13=49).',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Patterns',
    difficulty: 'Hard',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_logic_1',
    question: 'Rohan is 4th from the front in a queue and 9th from the back. How many children are in the queue altogether?',
    options: ['11', '12', '13', '14'],
    correctAnswer: '12',
    correctOptionIndex: 1,
    explanation: 'Add both positions and subtract 1 (because Rohan was counted twice): 4 + 9 - 1 = 12 children in total.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Logical Reasoning',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },
  {
    id: 'imo_g4_time_1',
    question: 'A cartoon show starts at 4:45 PM and lasts for 1 hour and 35 minutes. At what time does it finish?',
    options: ['6:15 PM', '6:20 PM', '6:10 PM', '6:25 PM'],
    correctAnswer: '6:20 PM',
    correctOptionIndex: 1,
    explanation: '4:45 PM + 1 hour = 5:45 PM. Then add 15 minutes to reach 6:00 PM. The remaining 20 minutes (35 - 15) brings us to 6:20 PM.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Time',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_money_1',
    question: 'A notebook costs $4 and a pen costs $1.50. Priya buys 3 notebooks and 2 pens. She pays with a $20 note. How much change will she receive?',
    options: ['$5.00', '$4.50', '$6.00', '$3.50'],
    correctAnswer: '$5.00',
    correctOptionIndex: 0,
    explanation: '3 notebooks = 3 × $4 = $12. 2 pens = 2 × $1.50 = $3. Total spent = $12 + $3 = $15. Change = $20 - $15 = $5.00.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Money',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_word_1',
    question: 'There are 5 birds on each branch of a tree. If there are 8 branches, and 6 birds fly away, how many birds remain?',
    options: ['40', '36', '34', '32'],
    correctAnswer: '34',
    correctOptionIndex: 2,
    explanation: 'Total initial birds = 5 × 8 = 40. When 6 birds fly away: 40 - 6 = 34 birds remain.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Word Problems',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 3 - IMO
  {
    id: 'imo_g3_num_1',
    question: 'What is the sum of the place values of 5 in the number 5,352?',
    options: ['500', '5,050', '5,500', '5,005'],
    correctAnswer: '5,050',
    correctOptionIndex: 1,
    explanation: 'In 5,352, the first 5 is in the thousands place (5,000) and the second 5 is in the tens place (50). The sum is 5,000 + 50 = 5,050.',
    subject: 'IMO',
    grade: 'Grade 3',
    topic: 'Numbers',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g3_mult_1',
    question: 'If 7 boxes each contain 6 crayons, how many crayons are there altogether?',
    options: ['36', '40', '42', '48'],
    correctAnswer: '42',
    correctOptionIndex: 2,
    explanation: 'Multiply the number of boxes by crayons per box: 7 × 6 = 42 crayons.',
    subject: 'IMO',
    grade: 'Grade 3',
    topic: 'Multiplication & Division',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - IMO
  {
    id: 'imo_g5_dec_1',
    question: 'Calculate: 3.45 + 0.8 - 1.25',
    options: ['2.90', '3.00', '3.10', '3.20'],
    correctAnswer: '3.00',
    correctOptionIndex: 1,
    explanation: '3.45 + 0.8 = 4.25. Then 4.25 - 1.25 = 3.00.',
    subject: 'IMO',
    grade: 'Grade 5',
    topic: 'Decimals',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g5_chall_1',
    question: 'In a farm, there are cows and ducks. Together they have 20 heads and 56 legs. How many cows are there?',
    options: ['6', '8', '10', '12'],
    correctAnswer: '8',
    correctOptionIndex: 1,
    explanation: 'Let cows be C and ducks be D. C + D = 20. Cows have 4 legs and ducks have 2 legs: 4C + 2D = 56. If all 20 were ducks: 20 × 2 = 40 legs. Extra legs = 56 - 40 = 16. Each cow gives 2 extra legs (4 - 2 = 2). Number of cows = 16 ÷ 2 = 8 cows!',
    subject: 'IMO',
    grade: 'Grade 5',
    topic: 'Logical Reasoning',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },

  // ==================== ISO (SCIENCE) ====================
  // 1. Plants
  {
    id: 'iso_g4_plant_1',
    question: 'Which green pigment in leaves captures sunlight to help plants prepare their own food?',
    options: ['Stomata', 'Chlorophyll', 'Glucose', 'Xylem'],
    correctAnswer: 'Chlorophyll',
    correctOptionIndex: 1,
    explanation: 'Chlorophyll is the green pigment inside plant chloroplasts that traps solar energy from sunlight during photosynthesis.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Plants',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_plant_2',
    question: 'Desert plants like cactus have spines instead of wide green leaves. What is the main reason for this adaptation?',
    options: ['To absorb more sunlight', 'To reduce water loss through transpiration', 'To attract insects for pollination', 'To store extra soil minerals'],
    correctAnswer: 'To reduce water loss through transpiration',
    correctOptionIndex: 1,
    explanation: 'Spines have very little surface area compared to broad leaves. This minimizes evaporation and water loss in dry, hot desert environments.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Plants',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_plant_3',
    question: 'Which of the following plants is insectivorous (traps and digests insects to obtain nitrogen)?',
    options: ['Money plant', 'Pitcher plant', 'Mushroom', 'Rose plant'],
    correctAnswer: 'Pitcher plant',
    correctOptionIndex: 1,
    explanation: 'Pitcher plants grow in nitrogen-deficient soil. They trap insects in their jug-shaped leaves and digest them to absorb nitrogen nutrients.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Plants',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // 2. Animals
  {
    id: 'iso_g4_anim_1',
    question: 'Which of the following animals breathes through both its moist skin in water and lungs on land?',
    options: ['Crocodile', 'Frog', 'Dolphin', 'Earthworm'],
    correctAnswer: 'Frog',
    correctOptionIndex: 1,
    explanation: 'Frogs are amphibians. On land they breathe using their lungs, while in water they absorb oxygen directly through their moist skin.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Animals',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_anim_2',
    question: 'Dolphins and whales live in the ocean, yet they come to the surface of the water regularly. Why?',
    options: ['To lay eggs in the air', 'To breathe in atmospheric oxygen with lungs', 'To cool down their body temperature', 'To search for flying insects'],
    correctAnswer: 'To breathe in atmospheric oxygen with lungs',
    correctOptionIndex: 1,
    explanation: 'Dolphins and whales are mammals, not fish. They do not possess gills and must breathe air into their lungs through blowholes at the surface.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Animals',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // 3. Food and Digestion
  {
    id: 'iso_g4_food_1',
    question: 'Where does the chemical digestion of food begin in the human body?',
    options: ['Stomach', 'Mouth (by saliva)', 'Small Intestine', 'Food pipe (Esophagus)'],
    correctAnswer: 'Mouth (by saliva)',
    correctOptionIndex: 1,
    explanation: 'Digestion begins right in the mouth! Saliva contains enzymes that start breaking down complex carbohydrates (starches) into simpler sugars.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Food and Digestion',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_food_2',
    question: 'In which organ of the human digestive system are most digested nutrients absorbed into the bloodstream?',
    options: ['Large intestine', 'Small intestine', 'Stomach', 'Liver'],
    correctAnswer: 'Small intestine',
    correctOptionIndex: 1,
    explanation: 'The small intestine has millions of tiny finger-like projections (villi) that absorb broken-down nutrients directly into circulating blood.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Food and Digestion',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_food_3',
    question: 'Which nutrient is known as the "body-building" nutrient responsible for muscle growth and cell repair?',
    options: ['Fats', 'Proteins', 'Carbohydrates', 'Roughage'],
    correctAnswer: 'Proteins',
    correctOptionIndex: 1,
    explanation: 'Proteins found in pulses, milk, eggs, and nuts are essential building blocks needed to grow new tissues and repair worn-out cells.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Food and Digestion',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // 4. Human Needs
  {
    id: 'iso_g4_needs_1',
    question: 'Why do humans wear light-colored cotton clothes during hot summer months?',
    options: [
      'Cotton absorbs sweat and light colors reflect heat',
      'Cotton traps heat and keeps body extra warm',
      'Cotton is completely waterproof against rain',
      'Cotton repels mosquitoes and flies'
    ],
    correctAnswer: 'Cotton absorbs sweat and light colors reflect heat',
    correctOptionIndex: 0,
    explanation: 'Cotton fibers are porous and absorb sweat, allowing it to evaporate and cool the skin. Light colors reflect most solar radiation, keeping us cooler.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_2',
    question: 'Which of the following is an essential habit required to maintain dental hygiene and prevent tooth cavities?',
    options: [
      'Eating sticky candies before sleeping',
      'Brushing teeth twice daily and rinsing after meals',
      'Drinking very hot water immediately after cold juice',
      'Chewing raw betel nuts'
    ],
    correctAnswer: 'Brushing teeth twice daily and rinsing after meals',
    correctOptionIndex: 1,
    explanation: 'Brushing twice a day removes food particles and dental plaque, preventing bacteria from producing tooth-decaying acids.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_3',
    question: 'Houses built on tall wooden stilts (stilt houses) are commonly constructed in regions that experience:',
    options: [
      'Frequent heavy rainfall and regular flooding',
      'Extremely dry desert heat and sandstorms',
      'Freezing blizzards and deep snowdrifts',
      'High rocky volcanic mountains'
    ],
    correctAnswer: 'Frequent heavy rainfall and regular flooding',
    correctOptionIndex: 0,
    explanation: 'Stilt houses are raised above the ground on strong wooden poles so that floodwaters, heavy rains, and insects cannot enter the living space.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_4',
    question: 'Which of the following is the simplest and most effective traditional method to kill disease-causing germs in drinking water at home?',
    options: [
      'Boiling water for at least 10 minutes',
      'Freezing water into solid ice cubes',
      'Stirring water with a wooden spoon',
      'Exposing water to ceiling fans'
    ],
    correctAnswer: 'Boiling water for at least 10 minutes',
    correctOptionIndex: 0,
    explanation: 'Boiling water kills harmful bacteria, parasites, and viruses, making the water safe and sterile for drinking.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_5',
    question: 'Why do woolen clothes keep our bodies warm and cozy during cold winter days?',
    options: [
      'Wool generates its own electrical heating',
      'Wool fibers trap air, and trapped air is a poor conductor of body heat',
      'Wool allows cold outdoor wind to pass directly into our skin',
      'Wool absorbs cold air and turns it into steam'
    ],
    correctAnswer: 'Wool fibers trap air, and trapped air is a poor conductor of body heat',
    correctOptionIndex: 1,
    explanation: 'Wool fibers have crimps that trap pockets of air. Air is a poor conductor of heat (insulator), preventing body warmth from escaping into cold surroundings.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_6',
    question: 'What is the immediate first-aid step you should take if you accidentally touch a hot cooking pan and get a minor burn?',
    options: [
      'Hold the burned area under cool running tap water for 10-15 minutes',
      'Apply thick oily butter or toothpaste directly on the skin',
      'Pierce any blisters with a sewing pin',
      'Cover it tightly with dirty cloth'
    ],
    correctAnswer: 'Hold the burned area under cool running tap water for 10-15 minutes',
    correctOptionIndex: 0,
    explanation: 'Cool running water removes heat from the burned tissue, reduces pain, and prevents deeper skin damage. Never use ice, butter, or paste.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_7',
    question: 'Why do growing school children need 8 to 9 hours of quality sleep every night?',
    options: [
      'Sleep allows the body to repair tissues, consolidate memory, and release growth hormones',
      'Sleep stops the heart from pumping blood to give it rest',
      'Sleeping prevents the body from digesting food',
      'Sleeping reduces the amount of oxygen required permanently'
    ],
    correctAnswer: 'Sleep allows the body to repair tissues, consolidate memory, and release growth hormones',
    correctOptionIndex: 0,
    explanation: 'During deep sleep, the brain processes learned lessons and memories, worn-out cells are repaired, and growth hormone is actively secreted.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_8',
    question: 'Which of the following safety rules should always be followed when walking or crossing busy city roads?',
    options: [
      'Always cross at the zebra crossing when the pedestrian signal is green',
      'Run across the street from between parked cars without looking',
      'Listen to music through headphones on maximum volume while crossing',
      'Walk in the middle of the road facing away from oncoming traffic'
    ],
    correctAnswer: 'Always cross at the zebra crossing when the pedestrian signal is green',
    correctOptionIndex: 0,
    explanation: 'Zebra crossings designate safe walking corridors where vehicles are required to yield. Always look right, left, and right again before crossing.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_9',
    question: 'What is the most important benefit of maintaining an upright, straight posture while sitting and reading at a desk?',
    options: [
      'It keeps the spine naturally aligned and prevents back and neck fatigue',
      'It makes human bones grow twice as fast',
      'It stops muscles from contracting',
      'It eliminates the need for physical exercise'
    ],
    correctAnswer: 'It keeps the spine naturally aligned and prevents back and neck fatigue',
    correctOptionIndex: 0,
    explanation: 'Good posture maintains natural spinal curvature, reduces strain on back ligaments and muscles, and ensures optimal lung expansion.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_needs_10',
    question: 'A portable, temporary shelter made of canvas, nylon, or waterproof fabric supported by poles and ropes is called a:',
    options: ['Tent', 'Igloo', 'Houseboat', 'Apartment'],
    correctAnswer: 'Tent',
    correctOptionIndex: 0,
    explanation: 'Tents are lightweight, easily folded and carried temporary shelters used by campers, trekkers, and soldiers.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Human Needs',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // 5. Matter and Materials
  {
    id: 'iso_g4_matt_1',
    question: 'When water vapour cools down and turns back into tiny liquid droplets in the air, the process is called:',
    options: ['Evaporation', 'Precipitation', 'Condensation', 'Freezing'],
    correctAnswer: 'Condensation',
    correctOptionIndex: 2,
    explanation: 'Condensation occurs when a gas loses heat energy and transforms back into a liquid state, forming clouds or dew drops.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Matter and Materials',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_matt_2',
    question: 'Which state of matter has a fixed volume but takes the shape of whatever container it is poured into?',
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correctAnswer: 'Liquid',
    correctOptionIndex: 1,
    explanation: 'Liquids (like water and milk) have a definite volume, but their particles can slide past each other, allowing them to assume the shape of the container.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Matter and Materials',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // 6. Force, Work and Energy
  {
    id: 'iso_g4_force_1',
    question: 'Why do bicycle brakes make a rolling bike slow down and stop when pressed against the wheel rim?',
    options: ['Gravitational pull increases', 'Friction opposes the motion', 'Magnetic repulsion acts on tires', 'Air pressure drops instantly'],
    correctAnswer: 'Friction opposes the motion',
    correctOptionIndex: 1,
    explanation: 'When brake pads press against the rim, friction is created between the two surfaces. Friction always opposes motion, causing the bicycle to slow down.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Force, Work and Energy',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_force_2',
    question: 'In science, in which of the following situations is "Work" said to be done?',
    options: [
      'A boy pushes a heavy wall for an hour but it does not move',
      'A girl pushes a toy car and moves it across the floor',
      'A student sits reading a book quietly for 2 hours',
      'A guard stands motionless holding a flag'
    ],
    correctAnswer: 'A girl pushes a toy car and moves it across the floor',
    correctOptionIndex: 1,
    explanation: 'In physics, work is done only when an applied force causes an object to move through a distance. If there is no displacement, work done is zero.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Force, Work and Energy',
    difficulty: 'Hard',
    sourceType: 'generated',
  },

  // 7. Our Environment
  {
    id: 'iso_g4_env_1',
    question: 'Which of the following items is biodegradable and will decompose naturally in soil over time?',
    options: ['Plastic straw', 'Banana peel', 'Aluminium soda can', 'Glass bottle'],
    correctAnswer: 'Banana peel',
    correctOptionIndex: 1,
    explanation: 'Banana peels are organic matter that microorganisms in soil break down into natural compost. Plastics, glass, and aluminium do not decompose easily.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Our Environment',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  {
    id: 'iso_g4_env_2',
    question: 'What do the 3 R’s in waste management and environmental protection stand for?',
    options: [
      'Read, Remember, Repeat',
      'Reduce, Reuse, Recycle',
      'Reheat, Refill, Remove',
      'Replace, Repair, Reject'
    ],
    correctAnswer: 'Reduce, Reuse, Recycle',
    correctOptionIndex: 1,
    explanation: 'The 3 R’s stand for: Reduce (use less), Reuse (use items multiple times), and Recycle (process waste into new products).',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Our Environment',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // 8. Earth and Universe
  {
    id: 'iso_g4_earth_1',
    question: 'Earth experiences day and night primarily because of which planetary movement?',
    options: ['Revolution around the Sun', 'Rotation on its own tilted axis', 'Gravitational pull of the Moon', 'Shifting of the Earth’s tectonic plates'],
    correctAnswer: 'Rotation on its own tilted axis',
    correctOptionIndex: 1,
    explanation: 'Earth spins (rotates) on its own axis once every 24 hours. The side facing the Sun has daylight, while the side turned away has night.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Earth and Universe',
    difficulty: 'Medium',
    sourceType: 'previousYear',
  },
  {
    id: 'iso_g4_earth_2',
    question: 'Why does the Moon appear in different shapes (crescent, half, full) during different nights of the month?',
    options: [
      'The Moon changes its actual physical shape every week',
      'Clouds block portions of the Moon from Earth',
      'We see different amounts of the illuminated half as the Moon orbits Earth',
      'Earth’s shadow falls on the Moon every single night'
    ],
    correctAnswer: 'We see different amounts of the illuminated half as the Moon orbits Earth',
    correctOptionIndex: 2,
    explanation: 'Half of the Moon is always lit by the Sun. As the Moon orbits Earth once a month, our viewing angle changes, creating phases of the Moon.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Earth and Universe',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // 9. Logical Reasoning (Science Olympiad Section 1)
  {
    id: 'iso_g4_logic_1',
    question: 'Find the odd one out among the following based on animal characteristics:',
    options: ['Penguin', 'Bat', 'Ostrich', 'Sparrow'],
    correctAnswer: 'Bat',
    correctOptionIndex: 1,
    explanation: 'A bat is a mammal (gives birth to live young and nurses them with milk), while penguin, ostrich, and sparrow are all birds (Aves) that lay eggs.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Logical Reasoning',
    difficulty: 'Medium',
    sourceType: 'previousYear',
  },
  {
    id: 'iso_g4_logic_2',
    question: 'Complete the analogy: Plant : Photosynthesis :: Human : ?',
    options: ['Digestion and Respiration', 'Transpiration', 'Metamorphosis', 'Germination'],
    correctAnswer: 'Digestion and Respiration',
    correctOptionIndex: 0,
    explanation: 'Plants produce and process energy primarily via photosynthesis. Humans process food and obtain energy through digestion and cellular respiration.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'Logical Reasoning',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // 10. SOF 2025 Questions (Authentic Olympiad Exam Style)
  {
    id: 'iso_g4_sof2025_1',
    question: '[SOF 2025 Exam Style] Three identical potted plants P, Q, and R were placed in different conditions: P was kept in darkness with water; Q was in bright sunlight without water; R was in bright sunlight with water. Which plant will successfully perform photosynthesis and thrive after 5 days?',
    options: ['Plant P only', 'Plant Q only', 'Plant R only', 'Both Plant P and Plant Q'],
    correctAnswer: 'Plant R only',
    correctOptionIndex: 2,
    explanation: 'Photosynthesis requires both sunlight and water (along with carbon dioxide from air). Plant P lacks light and Plant Q lacks water. Only Plant R has both sunlight and water.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'SOF 2025 Questions',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },
  {
    id: 'iso_g4_sof2025_2',
    question: '[SOF 2025 Exam Style] Study the given food chain: Grass → Grasshopper → Frog → Snake → Eagle. If all the frogs in this ecosystem are removed by disease, what will most likely happen immediately?',
    options: [
      'Grasshopper population increases and snake population faces food shortage',
      'Grass population will rapidly increase',
      'Eagle population will double in number',
      'Both snakes and eagles will start eating grass'
    ],
    correctAnswer: 'Grasshopper population increases and snake population faces food shortage',
    correctOptionIndex: 0,
    explanation: 'Frogs eat grasshoppers and are eaten by snakes. Removing frogs means fewer grasshoppers are eaten (so grasshopper numbers soar) and snakes lose their primary prey.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'SOF 2025 Questions',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },
  {
    id: 'iso_g4_sof2025_3',
    question: '[SOF 2025 Exam Style] A metal spoon and a wooden pencil were placed inside a cup of hot chocolate. After 3 minutes, the outer end of the metal spoon felt significantly hotter than the wooden pencil. What does this experiment prove?',
    options: [
      'Wood is a better thermal conductor than metal',
      'Metal is a good conductor of heat, while wood is a poor conductor (insulator)',
      'Hot chocolate only transfers heat to shiny objects',
      'Wood absorbs all the heat and destroys it'
    ],
    correctAnswer: 'Metal is a good conductor of heat, while wood is a poor conductor (insulator)',
    correctOptionIndex: 1,
    explanation: 'Metals have high thermal conductivity, allowing heat to flow rapidly from hot chocolate to the handle. Wood is an insulator, so heat does not easily travel through it.',
    subject: 'ISO',
    grade: 'Grade 4',
    topic: 'SOF 2025 Questions',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },

  // Grade 3 - ISO
  {
    id: 'iso_g3_anim_1',
    question: 'Which of these animals is an herbivore (eats only plants)?',
    options: ['Lion', 'Cow', 'Eagle', 'Shark'],
    correctAnswer: 'Cow',
    correctOptionIndex: 1,
    explanation: 'Herbivores are animals that eat only grass, leaves, and plant materials. Cows eat grass, making them herbivores.',
    subject: 'ISO',
    grade: 'Grade 3',
    topic: 'Animals',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - ISO
  {
    id: 'iso_g5_env_1',
    question: 'What is the greenhouse effect, and how does it impact planet Earth?',
    options: ['It cools the polar ice caps', 'Gases trap heat in the atmosphere, keeping Earth warm', 'It blocks all solar radiation from entering', 'It makes plants grow without sunlight'],
    correctAnswer: 'Gases trap heat in the atmosphere, keeping Earth warm',
    correctOptionIndex: 1,
    explanation: 'Greenhouse gases like carbon dioxide and water vapor absorb infrared heat radiated from Earth’s surface, trapping warmth in the lower atmosphere.',
    subject: 'ISO',
    grade: 'Grade 5',
    topic: 'Our Environment',
    difficulty: 'Hard',
    sourceType: 'generated',
  },

  // ==================== ICSO (COMPUTER SCIENCE) ====================
  // Grade 4 - Hardware
  {
    id: 'icso_g4_hard_1',
    question: 'Which component is commonly known as the "Brain" of the computer that performs calculations and carries out instructions?',
    options: ['RAM', 'Hard Drive', 'CPU (Central Processing Unit)', 'Motherboard'],
    correctAnswer: 'CPU (Central Processing Unit)',
    correctOptionIndex: 2,
    explanation: 'The CPU processes commands, calculates arithmetic equations, and manages operations, just like a brain coordinates the human body.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Hardware',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Input & Output Devices
  {
    id: 'icso_g4_io_1',
    question: 'Which of the following devices is solely an OUTPUT device?',
    options: ['Keyboard', 'Microphone', 'Monitor', 'Webcam'],
    correctAnswer: 'Monitor',
    correctOptionIndex: 2,
    explanation: 'A monitor displays visual output to the user. Keyboards, microphones, and webcams are input devices used to feed data into the computer.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Input & Output Devices',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Cyber Safety
  {
    id: 'icso_g4_cyber_1',
    question: 'Which of the following is the SAFEST password to use for an online learning account?',
    options: ['123456', 'myname123', 'B!ueSky#94', 'password'],
    correctAnswer: 'B!ueSky#94',
    correctOptionIndex: 2,
    explanation: 'A strong password combines uppercase letters, lowercase letters, numbers, and special symbols (! or #), making it very hard for unauthorized persons to guess.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Cyber Safety',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'icso_g4_cyber_2',
    question: 'If a stranger in an online multiplayer game asks you for your home address or phone number, what should you do?',
    options: [
      'Share it only if they seem friendly',
      'Never share personal info and tell a parent or teacher immediately',
      'Give them a friend’s address instead',
      'Ask them for their phone number first'
    ],
    correctAnswer: 'Never share personal info and tell a parent or teacher immediately',
    correctOptionIndex: 1,
    explanation: 'Never share your real name, address, school, or phone number online. Always inform a trusted adult if an unknown person asks for private information.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Cyber Safety',
    difficulty: 'Easy',
    sourceType: 'generated',
  },
  // Grade 4 - Algorithms & Logic
  {
    id: 'icso_g4_algo_1',
    question: 'In computer science, what is an "Algorithm"?',
    options: [
      'A special computer monitor screen',
      'A step-by-step set of instructions to solve a problem',
      'A virus that erases all files',
      'A computer power cable'
    ],
    correctAnswer: 'A step-by-step set of instructions to solve a problem',
    correctOptionIndex: 1,
    explanation: 'An algorithm is an ordered sequence of clear instructions or steps designed to accomplish a specific task, such as a recipe or coding instructions.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Algorithms',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'icso_g4_code_1',
    question: 'A robot is programmed with this loop: REPEAT 4 TIMES [Move forward 1 step, Turn right 90 degrees]. What geometric shape will the robot trace on the floor?',
    options: ['Triangle', 'Square', 'Circle', 'Hexagon'],
    correctAnswer: 'Square',
    correctOptionIndex: 1,
    explanation: 'A square has 4 equal sides and four 90-degree right angle corners. Moving forward and turning 90 degrees 4 times returns the robot to the start in a square shape.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Coding Basics',
    difficulty: 'Hard',
    sourceType: 'previousYear',
  },
  {
    id: 'icso_g4_comp_1',
    question: 'Look at the sequence: 1010, 1020, 1040, 1070, ____. What is the next number in this sequence?',
    options: ['1090', '1100', '1110', '1120'],
    correctAnswer: '1110',
    correctOptionIndex: 2,
    explanation: 'Examine the differences between consecutive terms: 1020 - 1010 = +10, 1040 - 1020 = +20, 1070 - 1040 = +30. The next jump should be +40! So 1070 + 40 = 1110.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Computational Thinking',
    difficulty: 'Olympiad Challenge',
    sourceType: 'generated',
  },

  // Grade 3 - ICSO
  {
    id: 'icso_g3_basic_1',
    question: 'Which key on the keyboard is used to create a blank space between two words?',
    options: ['Enter Key', 'Spacebar', 'Shift Key', 'Backspace'],
    correctAnswer: 'Spacebar',
    correctOptionIndex: 1,
    explanation: 'The spacebar is the longest key on the keyboard, located at the bottom center. Pressing it inserts a single space between words.',
    subject: 'ICSO',
    grade: 'Grade 3',
    topic: 'Computer Basics',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // Grade 5 - ICSO
  {
    id: 'icso_g5_net_1',
    question: 'What is the primary function of a Web Browser like Chrome or Firefox?',
    options: [
      'To build physical computer chips',
      'To retrieve, format, and display webpages from the internet',
      'To clean viruses from the hard drive',
      'To create PowerPoint presentations automatically'
    ],
    correctAnswer: 'To retrieve, format, and display webpages from the internet',
    correctOptionIndex: 1,
    explanation: 'A web browser is an application software used to navigate the World Wide Web, interpret HTML/CSS code, and render interactive webpages on your screen.',
    subject: 'ICSO',
    grade: 'Grade 5',
    topic: 'Internet',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // ==================== ADDITIONAL COMPREHENSIVE CURATED TOPICS ====================
  // IMO: Addition & Subtraction
  {
    id: 'imo_g4_add_1',
    question: 'A train had 485 passengers. At the first station, 128 passengers got off and 95 new passengers boarded. How many passengers are on the train now?',
    options: ['452', '448', '462', '458'],
    correctAnswer: '452',
    correctOptionIndex: 0,
    explanation: '485 passengers - 128 left = 357 passengers. Then 357 + 95 joined = 452 passengers remaining.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Addition & Subtraction',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_add_2',
    question: 'Find the difference between the greatest 4-digit number and the smallest 4-digit number that can be formed using digits 3, 8, 0, 5 without repeating digits.',
    options: ['5,472', '5,787', '5,427', '5,742'],
    correctAnswer: '5,472',
    correctOptionIndex: 0,
    explanation: 'Greatest 4-digit number is 8,530. Smallest 4-digit number is 3,058 (0 cannot be the first digit). Difference: 8,530 - 3,058 = 5,472.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Addition & Subtraction',
    difficulty: 'Olympiad Challenge',
    sourceType: 'previousYear',
  },

  // IMO: Measurement
  {
    id: 'imo_g4_meas_1',
    question: 'A water bottle contains 1 litre 250 ml of water. If Vihaan drinks 450 ml, how much water is left in the bottle?',
    options: ['800 ml', '750 ml', '850 ml', '900 ml'],
    correctAnswer: '800 ml',
    correctOptionIndex: 0,
    explanation: '1 litre 250 ml = 1,250 ml. 1,250 ml - 450 ml = 800 ml remaining.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Measurement',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
  {
    id: 'imo_g4_meas_2',
    question: 'Rhea needs 3 ribbons of length 1 m 40 cm each. What is the total length of ribbon needed in meters and centimeters?',
    options: ['4 m 20 cm', '3 m 80 cm', '4 m 40 cm', '4 m 60 cm'],
    correctAnswer: '4 m 20 cm',
    correctOptionIndex: 0,
    explanation: '3 × 1 m = 3 m. 3 × 40 cm = 120 cm = 1 m 20 cm. Total = 3 m + 1 m 20 cm = 4 m 20 cm.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Measurement',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // IMO: Data Interpretation
  {
    id: 'imo_g4_data_1',
    question: 'In a pictograph, 1 star represents 5 books read. If Class 4 has 7 stars next to their name, how many books did they read?',
    options: ['28', '30', '35', '40'],
    correctAnswer: '35',
    correctOptionIndex: 2,
    explanation: 'Since 1 star = 5 books, 7 stars = 7 × 5 = 35 books.',
    subject: 'IMO',
    grade: 'Grade 4',
    topic: 'Data Interpretation',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // ICSO: Operating Systems
  {
    id: 'icso_g4_os_1',
    question: 'Which of the following is an open-source operating system whose mascot is a penguin named Tux?',
    options: ['Windows', 'Linux', 'macOS', 'iOS'],
    correctAnswer: 'Linux',
    correctOptionIndex: 1,
    explanation: 'Linux is a renowned open-source operating system whose official mascot is Tux the penguin.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Operating Systems',
    difficulty: 'Medium',
    sourceType: 'generated',
  },

  // ICSO: Software
  {
    id: 'icso_g4_soft_1',
    question: 'Software designed to detect, quarantine, and eliminate harmful viruses from a computer is called:',
    options: ['Antivirus software', 'Operating system', 'Word processor', 'Web browser'],
    correctAnswer: 'Antivirus software',
    correctOptionIndex: 0,
    explanation: 'Antivirus software scans drives and memory to identify and remove malicious computer worms, spyware, and viruses.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Software',
    difficulty: 'Easy',
    sourceType: 'generated',
  },

  // ICSO: Logical Thinking
  {
    id: 'icso_g4_logth_1',
    question: 'If CAT is coded as 3-1-20 in a secret alphabet code (A=1, B=2, C=3...), what will DOG be coded as?',
    options: ['4-15-7', '4-14-7', '3-15-7', '4-15-8'],
    correctAnswer: '4-15-7',
    correctOptionIndex: 0,
    explanation: 'D is 4th letter, O is 15th letter, and G is 7th letter. Therefore DOG = 4-15-7.',
    subject: 'ICSO',
    grade: 'Grade 4',
    topic: 'Logical Thinking',
    difficulty: 'Medium',
    sourceType: 'generated',
  },
];
