import { SubjectConfig, SubjectId, Grade, Difficulty, BadgeDefinition } from '../types';

export const GRADES: Grade[] = ['Grade 3', 'Grade 4', 'Grade 5'];

export const DIFFICULTIES: Difficulty[] = [
  'Easy',
  'Medium',
  'Hard',
  'Olympiad Challenge',
];

export const SUBJECT_CONFIGS: Record<SubjectId, SubjectConfig> = {
  IMO: {
    id: 'IMO',
    name: 'IMO',
    fullName: 'International Mathematics Olympiad',
    emoji: '🧮',
    tagline: 'Numbers, logic, geometry & puzzles!',
    themeColor: 'amber',
    accentBg: 'bg-amber-500',
    borderColor: 'border-amber-400',
    textColor: 'text-amber-700',
    topics: [
      'Numbers',
      'Addition & Subtraction',
      'Multiplication & Division',
      'Fractions',
      'Decimals',
      'Geometry',
      'Measurement',
      'Time',
      'Money',
      'Patterns',
      'Logical Reasoning',
      'Data Interpretation',
      'Word Problems',
    ],
  },
  ISO: {
    id: 'ISO',
    name: 'ISO',
    fullName: 'International Science Olympiad',
    emoji: '🔬',
    tagline: 'Explore nature, universe, matter & life!',
    themeColor: 'emerald',
    accentBg: 'bg-emerald-500',
    borderColor: 'border-emerald-400',
    textColor: 'text-emerald-700',
    topics: [
      'Plants',
      'Animals',
      'Food and Digestion',
      'Human Needs',
      'Matter and Materials',
      'Force, Work and Energy',
      'Our Environment',
      'Earth and Universe',
      'Logical Reasoning',
      'SOF 2025 Questions',
    ],
  },
  ICSO: {
    id: 'ICSO',
    name: 'ICSO',
    fullName: 'International Computer Science Olympiad',
    emoji: '💻',
    tagline: 'Coding logic, cyber safety, hardware & algorithms!',
    themeColor: 'indigo',
    accentBg: 'bg-indigo-500',
    borderColor: 'border-indigo-400',
    textColor: 'text-indigo-700',
    topics: [
      'Computer Basics',
      'Hardware',
      'Software',
      'Input & Output Devices',
      'Operating Systems',
      'Internet',
      'Cyber Safety',
      'Algorithms',
      'Logical Thinking',
      'Coding Basics',
      'Patterns',
      'Computational Thinking',
    ],
  },
};

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  {
    id: 'first_step',
    name: 'First Step',
    description: 'Answered your very first Olympiad question!',
    emoji: '🌱',
    color: 'emerald',
    criteria: (p) => p.totalQuestionsAttempted >= 1,
  },
  {
    id: 'first_10',
    name: 'First 10 Questions',
    description: 'Completed 10 questions of Olympiad practice',
    emoji: '🌟',
    color: 'amber',
    criteria: (p) => p.totalQuestionsAttempted >= 10,
  },
  {
    id: 'math_explorer',
    name: 'Math Explorer',
    description: 'Answered 10+ IMO Mathematics questions correctly',
    emoji: '🧮',
    color: 'amber',
    criteria: (p) => (p.subjectStats.IMO?.correct || 0) >= 10,
  },
  {
    id: 'science_star',
    name: 'Science Star',
    description: 'Answered 10+ ISO Science questions correctly',
    emoji: '🔬',
    color: 'emerald',
    criteria: (p) => (p.subjectStats.ISO?.correct || 0) >= 10,
  },
  {
    id: 'computer_champ',
    name: 'Computer Champ',
    description: 'Answered 10+ ICSO Computer Science questions correctly',
    emoji: '💻',
    color: 'indigo',
    criteria: (p) => (p.subjectStats.ICSO?.correct || 0) >= 10,
  },
  {
    id: 'streak_3',
    name: '3 Day Streak',
    description: 'Practiced 3 days in a row',
    emoji: '🔥',
    color: 'orange',
    criteria: (p) => p.streak >= 3 || p.longestStreak >= 3,
  },
  {
    id: 'streak_7',
    name: '7 Day Streak',
    description: 'Kept up your daily learning streak for a full week!',
    emoji: '⚡',
    color: 'rose',
    criteria: (p) => p.streak >= 7 || p.longestStreak >= 7,
  },
  {
    id: 'master_50',
    name: '50 Questions Master',
    description: 'Attempted 50 questions with determination',
    emoji: '🏆',
    color: 'purple',
    criteria: (p) => p.totalQuestionsAttempted >= 50,
  },
  {
    id: 'master_100',
    name: '100 Questions Master',
    description: 'Champion status: 100 questions attempted!',
    emoji: '👑',
    color: 'yellow',
    criteria: (p) => p.totalQuestionsAttempted >= 100,
  },
  {
    id: 'perfect_score',
    name: 'Perfect Score',
    description: 'Scored 100% on a practice session or mock test',
    emoji: '🎯',
    color: 'blue',
    criteria: (p) =>
      p.mockExamHistory.some((m) => m.scorePercentage === 100) ||
      (p.totalCorrect >= 10 && p.totalCorrect === p.totalQuestionsAttempted),
  },
];
